### ISSUE TITLE
Server used for authentication is too insecure for modern node versions

### ISSUE THREAD

**Issue by ncovercash** [ssut/wideq-js#13]
I can not seem to get a line in the source where this happens, however, once I paste in my resulting URL I get an unsupported protocol error:

```
Error: write EPROTO 139732908562304:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1942:
```

From research, this seems to be a SSL protocol mismatch.  If I add `--tls-min-v1.0` when I run node (e.g. `node --tls-min-v1.0 --trace-warnings cli.js auth` the warning is not present.  Is there any way to get around this without this argument?

**Comment by bayramog** [comment]
You can see [this one](https://github.com/sampsyo/wideq/issues/60).

**Comment by ncovercash** [comment]
Alright, thanks!
